### ISSUE TITLE
Several PageIndicatorView in same view, only the first one works

### ISSUE THREAD

**Issue by amanzan** [romandanylyk/PageIndicatorView#52] opened 2017-07-21 10:50 UTC
I have a view with 2 ViewPagers, each one with its own PageIndicatorView. Only the first one works and it actually makes the second one to move at the same time. When I swipe on the second ViewPager, the PageIndicatorView does nothing

**Comment by endy-s** [comment] 2017-07-27 19:16
I have a similar problem. I use the PageIndicatorView for ViewPagers that are inside of RecyclerViews. 
It gets the first one "status" and reproduce it to the following ones, until I scroll the screen, where they all "reorganize" for the right behavior.

In this case, the first item of the RecyclerView have set the PageIndicatorView visibility to false, so the second item doesn't show it.
<img src="https://user-images.githubusercontent.com/10025997/28687763-e3183db2-72e5-11e7-912e-2797809f4a51.png" width="200" height="400"/>

This is the same screen after scrolling down and back up. This is the right behavior, showing the PageIndicatorView at the bottom left of the RecyclerView item.
<img src="https://user-images.githubusercontent.com/10025997/28687822-1d3494d2-72e6-11e7-923b-1262a52aadcb.png" width="200" height="400"/>

If the first item haves an PageIndicatorView and I scroll my ViewPager, it makes all the other item's PageIndicatorView to move with it.

Hope to hear something from you guys :)

**Comment by romandanylyk** [comment] 2017-07-29 19:19
Hi guys, having issues with PageIndicatorView in views that have 2 or more view pager's could be caused by id conflicts, you specified in your layout xml. In this case you could try to handle selected item or PageIndicatorView manually by calling it's public methods instead of setting ViewPager id in xml.
Hope it helps.

**Comment by endy-s** [comment] 2017-07-29 21:43
@romandanylyk Thanks for your answer!
I changed the `app:piv_viewPager="@+id/viewPager"` for `app:piv_count="2"`, changed the selection at the View Pager listener and it worked as expected.

I think that if this info is at the Readme it would help other people that can face this issue. I created [this PR](https://github.com/romandanylyk/PageIndicatorView/pull/53) for it 😄

**Comment by romandanylyk** [comment] 2017-10-26 21:07
@endy-s @amanzan since issues is resolved I'll close this one.

**Closed by romandanylyk** 2017-10-26 21:07 UTC
